site_name: CSWHTM
theme:
  name: material

  icon: 
    logo:material/lightbulb

  palette:
    primary: teal

copyright: copyright@ 2Zoige Plateau Wetlands Ecosystem Research Station, Northwest Institute of Eco-Environment and Resources, Chinese Academy of Sciences. All Rights Reserved